# Generated by Django 4.2.1 on 2025-08-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
            ],
        ),
    ]
