version: '3.7'

services:
  backend:
    build: ./backend
    container_name: "backend-app-dev"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - '8000:8000'
      - '30000:30000'
    networks:
      - dev
    depends_on:
      - db
    env_file:
      - ./.env.dev
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: "frontend-dev"
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    networks:
      - dev
    ports:
      - '3000:3000'
      - '31000:31000'
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - "backend"
    command:
      npm start

  db:
    # image: postgres:13.2-alpine
    image: postgres:15.3-alpine
    container_name: "db-dev"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dev
    environment:
      - POSTGRES_USER=postgres_dev
      - POSTGRES_PASSWORD=postgres_dev
      - POSTGRES_DB=postgres_dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin-dev"
    # restart: on-failure
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres_dev@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres_dev
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - dev

volumes:
  postgres_data:
  node-modules:

networks:
  dev:
